name: netflixstats;

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: joeldocker485/netflixstats
    container_name: express-app
    ports: 
      - 3000:3000
    environment:
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - CONNECTION=${CONNECTION}
    depends_on: 
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    image: joeldocker485/mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    expose:
      - '3306'
   