name: netflixstars;

services:
  app:
    # image: netflixstats:test
    build: .
    container_name: express-app
    ports: 
      - 3000:3000
    environment:
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - CONNECTION=${CONNECTION}
    depends_on: 
      - db
  db:
    image: mysql:8.4
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/ #OMIT later
      - ./upload:/var/lib/mysql-files/ #OMIT later
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    expose:
      - '3306'
   